id: AA24ADC3B
base_file: fCE30.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:26:36.742062
  last_modified_at: 2022-06-17 14:26:36.742070
