id: AA24ADC3B
base_file: f6DDA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:26:36.700019
  last_modified_at: 2022-06-17 14:26:36.700034
