id: AA24ADC3B
base_file: fAEC8.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:26:36.737220
  last_modified_at: 2022-06-17 14:26:36.737231
